stages:
  - test

test:
  stage: test
  tags:
    - generic
  image: "debian:bullseye-slim"
  script:
    - bash ./bootstrap.sh
    - sudo --user ansible whoami
    - sudo --user ansible sudo apt-get update
