stages:
  - test

test:
  stage: test
  tags:
    - generic
  image: "debian:bullseye-slim"
  script:
    - bash ./bootstrap.sh
    - su - ansible
    - whoami | grep "ansible"
    - sudo apt-get update
